server:
  port: 8081

spring: 
  application:
     name : course-service
     
  zipkin:
    enabled: true

  datasource: 
    url : jdbc:sqlserver://10.130.34.160:1433;databaseName=paymanager;CharacterSet=UTF-8
    username : sa
    password : 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa: 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2008Dialect
        connection: 
          characterEncoding: UTF-8
          CharSet: UTF-8
          useUnicode: true
    show-sql: true 
    hibernate:
      ddl-auto: none
      
      

 
#    
#    
# enables Spring Boot Actuator end points
management:
  endpoints:
    web:
      exposure:
        include: "*"        
     

      
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.istio-system.svc.cluster.local:8761/eureka